version: '3.7'
services:
  db:
    image: postgres:12.5-alpine
    volumes:
    - .:/dockerDRF
  api:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 127.0.0.1:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db