# Generated by Django 3.0.5 on 2020-12-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
