# Generated by Django 3.0.5 on 2020-12-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20201223_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
