# Generated by Django 3.0.5 on 2020-12-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
