# Generated by Django 3.0.5 on 2020-12-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20201228_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='like',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='like_or_dislike',
            field=models.CharField(choices=[('Like', 'like'), ('Dislike', 'dislike'), (None, 'None')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
    ]
